fix: Cron Build (#189)

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,24 +1,19 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
 export HNVM_PNPM=10.17.1
 
 echo "🧪 Running pre-push checks..."
 
 cd "$(git rev-parse --show-toplevel)" || exit
 
-for dir in client server cron; do
+echo "🔬 Running tests..."
 
-  # Install dependencies to avoid problems with dependencies
-  echo "🔬 Running tests in $dir..."
-  npx pnpm --filter=$dir --if-present run test
+pnpm -r --if-present run test
 
-  if [ $? -eq 0 ]; then
-    echo "✅ All tests passed in $dir!"
-  else
-    echo "❌ Tests failed in $dir! Please fix failing tests before pushing."
-    exit 1
-  fi
-done
+if [ $? -eq 0 ]; then
+  echo "✅ All tests passed!"
+else
+  echo "❌ Tests failed! Please fix failing tests before pushing."
+  exit 1
+fi
 
 echo "✅ Pre-push checks completed successfully!"
